import Head from "next/head";
import { getProviders, signIn } from "next-auth/react";

export default function SignIn() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <div className="block max-w-sm rounded-lg bg-white p-6 shadow-lg">
          <>
            <div key="google">
              <button
                type="submit"
                className="
                      inline-flex
                      w-full
                      items-center
                      rounded
                      px-6
                      py-2.5
                      font-medium
                      leading-tight shadow-md
                      transition duration-150 ease-in-out hover:bg-gray-100
                      hover:shadow-lg focus:bg-gray-100
                      focus:shadow-lg
                      focus:outline-none
                      focus:ring-0
                      active:bg-gray-200 active:shadow-lg"
                onClick={() => signIn("google")}
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 488 512"
                  className="h-5 w-5 fill-gray-700"
                >
                  <path d="M488 261.8C488 403.3 391.1 504 248 504 110.8 504 0 393.2 0 256S110.8 8 248 8c66.8 0 123 24.5 166.3 64.9l-67.5 64.9C258.5 52.6 94.3 116.6 94.3 256c0 86.5 69.1 156.6 153.7 156.6 98.2 0 135-70.4 140.8-106.9H248v-85.3h236.1c2.3 12.7 3.9 24.9 3.9 41.4z" />
                </svg>
                <div className="p-1"></div>
                <span>Log in With Google</span>
              </button>
            </div>
          </>
        </div>
      </div>
    </>
  );
}
