import Head from "next/head";
import { getProviders, signIn } from "next-auth/react";

export async function getServerSideProps() {
  const providers = await getProviders();
  return {
    props: { providers },
  };
}

export default function SignIn({ providers }: any) {
  // const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);
  console.log("providers: ", providers);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <div className="block p-6 rounded-lg shadow-lg bg-white max-w-sm">
          <>
            {Object.values(providers).map((provider: any) => (
              <div key={provider.name}>
                <button
                  type="submit"
                  className="
                      w-full
                      px-6
                      py-2.5
                      font-medium
                      leading-tight
                      rounded
                      shadow-md
                      hover:bg-gray-100 hover:shadow-lg
                      focus:bg-gray-100 focus:shadow-lg focus:outline-none focus:ring-0
                      active:bg-gray-200 active:shadow-lg
                      transition
                      duration-150
                      ease-in-out
                      inline-flex items-center"
                  onClick={() => signIn(provider.id)}
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 488 512"
                    className="w-5 h-5 fill-gray-700"
                  >
                    <path d="M488 261.8C488 403.3 391.1 504 248 504 110.8 504 0 393.2 0 256S110.8 8 248 8c66.8 0 123 24.5 166.3 64.9l-67.5 64.9C258.5 52.6 94.3 116.6 94.3 256c0 86.5 69.1 156.6 153.7 156.6 98.2 0 135-70.4 140.8-106.9H248v-85.3h236.1c2.3 12.7 3.9 24.9 3.9 41.4z" />
                  </svg>
                  <div className="p-1"></div>
                  <span>Log in With {provider.name}</span>
                </button>
              </div>
            ))}
          </>
        </div>
      </main>
    </>
  );
}
